# Generated by Django 3.2.6 on 2023-03-14 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20230314_1713'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='fathers_name',
            new_name='father_name',
        ),
    ]
